import type { Metadata } from 'next';
import './globals.css';
import MouseOverlay from '@/components/MouseOverlay/MouseOverlay';
import SmoothScroll from '@/components/SmothScroll/SmothScroll';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MouseOverlay />

        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
